Google_Play Analysis

Step 1 : Import Requirement Libraise

In [1]:
import numpy as np
import pandas as pd

Step 2 : Import Dataset & Backup

In [2]:
Google_Play=pd.read_csv(r"C:\Users\Lap Tech\Desktop\Google Play\googleplaystore.csv")

Google_Play_Backup=Google_Play.copy()

Step 3 : EDA ( Explory Dataset )

In [3]:
Google_Play.info()

<class 'pandas.DataFrame'>
RangeIndex: 10841 entries, 0 to 10840
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   App             10841 non-null  str
 1   Category        10840 non-null  str
 2   Rating          9367 non-null   float64
 3   Reviews         10841 non-null  int64
 4   Size            10841 non-null  str
 5   Installs        10841 non-null  str
 6   Type            10840 non-null  str
 7   Price           10841 non-null  str
 8   Content Rating  10841 non-null  str
 9   Genres          10840 non-null  str
 10  Last Updated    10841 non-null  str
 11  Current Ver     10832 non-null  str
 12  Android Ver     10839 non-null  str
dtypes: float64(1), int64(1), str(11)
memory usage: 1.1 MB

In [4]:
Google_Play.head(50)

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19M,"10,000+",Free,0,Everyone,Art & Design,1/7/2018,1.0.0,4.0.3 and up
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14M,"500,000+",Free,0,Everyone,Art & Design;Pretend Play,1/15/2018,2.0.0,4.0.3 and up
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7M,"5,000,000+",Free,0,Everyone,Art & Design,8/1/2018,1.2.4,4.0.3 and up
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25M,"50,000,000+",Free,0,Teen,Art & Design,6/8/2018,Varies with device,4.2 and up
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8M,"100,000+",Free,0,Everyone,Art & Design;Creativity,6/20/2018,1.1,4.4 and up
5,Paper flowers instructions,ART_AND_DESIGN,4.4,167,5.6M,"50,000+",Free,0,Everyone,Art & Design,3/26/2017,1,2.3 and up
6,Smoke Effect Photo Maker - Smoke Editor,ART_AND_DESIGN,3.8,178,19M,"50,000+",Free,0,Everyone,Art & Design,4/26/2018,1.1,4.0.3 and up
7,Infinite Painter,ART_AND_DESIGN,4.1,36815,29M,"1,000,000+",Free,0,Everyone,Art & Design,6/14/2018,6.1.61.1,4.2 and up
8,Garden Coloring Book,ART_AND_DESIGN,4.4,13791,33M,"1,000,000+",Free,0,Everyone,Art & Design,9/20/2017,2.9.2,3.0 and up
9,Kids Paint Free - Drawing Fun,ART_AND_DESIGN,4.7,121,3.1M,"10,000+",Free,0,Everyone,Art & Design;Creativity,7/3/2018,2.8,4.0.3 and up
10,Text on Photo - Fonteee,ART_AND_DESIGN,4.4,13880,28M,"1,000,000+",Free,0,Everyone,Art & Design,10/27/2017,1.0.4,4.1 and up
11,Name Art Photo Editor - Focus n Filters,ART_AND_DESIGN,4.4,8788,12M,"1,000,000+",Free,0,Everyone,Art & Design,7/31/2018,1.0.15,4.0 and up
12,Tattoo Name On My Photo Editor,ART_AND_DESIGN,4.2,44829,20M,"10,000,000+",Free,0,Teen,Art & Design,4/2/2018,3.8,4.1 and up
13,Mandala Coloring Book,ART_AND_DESIGN,4.6,4326,21M,"100,000+",Free,0,Everyone,Art & Design,6/26/2018,1.0.4,4.4 and up
14,3D Color Pixel by Number - Sandbox Art Coloring,ART_AND_DESIGN,4.4,1518,37M,"100,000+",Free,0,Everyone,Art & Design,8/3/2018,1.2.3,2.3 and up
15,Learn To Draw Kawaii Characters,ART_AND_DESIGN,3.2,55,2.7M,"5,000+",Free,0,Everyone,Art & Design,6/6/2018,NaN,4.2 and up
16,Photo Designer - Write your name with shapes,ART_AND_DESIGN,4.7,3632,5.5M,"500,000+",Free,0,Everyone,Art & Design,7/31/2018,3.1,4.1 and up
17,350 Diy Room Decor Ideas,ART_AND_DESIGN,4.5,27,17M,"10,000+",Free,0,Everyone,Art & Design,11/7/2017,1,2.3 and up
18,FlipaClip - Cartoon animation,ART_AND_DESIGN,4.3,194216,39M,"5,000,000+",Free,0,Everyone,Art & Design,8/3/2018,2.2.5,4.0.3 and up
19,ibis Paint X,ART_AND_DESIGN,4.6,224399,31M,"10,000,000+",Free,0,Everyone,Art & Design,7/30/2018,5.5.4,4.1 and up
20,Logo Maker - Small Business,ART_AND_DESIGN,4.0,450,14M,"100,000+",Free,0,Everyone,Art & Design,4/20/2018,4,4.1 and up
21,Boys Photo Editor - Six Pack & Men's Suit,ART_AND_DESIGN,4.1,654,12M,"100,000+",Free,0,Everyone,Art & Design,3/20/2018,1.1,4.0.3 and up
22,Superheroes Wallpapers | 4K Backgrounds,ART_AND_DESIGN,4.7,7699,4.2M,"500,000+",Free,0,Everyone 10+,Art & Design,7/12/2018,2.2.6.2,4.0.3 and up
23,Mcqueen Coloring pages,ART_AND_DESIGN,NaN,61,7.0M,"100,000+",Free,0,Everyone,Art & Design;Action & Adventure,3/7/2018,1.0.0,4.1 and up
24,HD Mickey Minnie Wallpapers,ART_AND_DESIGN,4.7,118,23M,"50,000+",Free,0,Everyone,Art & Design,7/7/2018,1.1.3,4.1 and up
25,Harley Quinn wallpapers HD,ART_AND_DESIGN,4.8,192,6.0M,"10,000+",Free,0,Everyone,Art & Design,4/25/2018,1.5,3.0 and up
26,Colorfit - Drawing & Coloring,ART_AND_DESIGN,4.7,20260,25M,"500,000+",Free,0,Everyone,Art & Design;Creativity,10/11/2017,1.0.8,4.0.3 and up
27,Animated Photo Editor,ART_AND_DESIGN,4.1,203,6.1M,"100,000+",Free,0,Everyone,Art & Design,3/21/2018,1.03,4.0.3 and up
28,Pencil Sketch Drawing,ART_AND_DESIGN,3.9,136,4.6M,"10,000+",Free,0,Everyone,Art & Design,7/12/2018,6,2.3 and up
29,Easy Realistic Drawing Tutorial,ART_AND_DESIGN,4.1,223,4.2M,"100,000+",Free,0,Everyone,Art & Design,8/22/2017,1,2.3 and up
30,Pink Silver Bow Keyboard Theme,ART_AND_DESIGN,4.2,1120,9.2M,"100,000+",Free,0,Everyone,Art & Design,7/12/2018,6.7.12.2018,4.0.3 and up
31,Art Drawing Ideas,ART_AND_DESIGN,4.1,227,5.2M,"50,000+",Free,0,Everyone,Art & Design,5/31/2018,1.2,2.3 and up
32,Anime Manga Coloring Book,ART_AND_DESIGN,4.5,5035,11M,"100,000+",Free,0,Everyone,Art & Design,7/19/2018,2.2,4.0 and up
33,Easy Origami Ideas,ART_AND_DESIGN,4.2,1015,11M,"100,000+",Free,0,Everyone,Art & Design,1/6/2018,1.1.0,4.1 and up
34,I Creative Idea,ART_AND_DESIGN,4.7,353,4.2M,"10,000+",Free,0,Teen,Art & Design,4/27/2018,1.6,4.1 and up
35,How to draw Ladybug and Cat Noir,ART_AND_DESIGN,3.8,564,9.2M,"100,000+",Free,0,Everyone,Art & Design,7/11/2018,2.1,4.1 and up
36,UNICORN - Color By Number & Pixel Art Coloring,ART_AND_DESIGN,4.7,8145,24M,"500,000+",Free,0,Everyone,Art & Design;Creativity,8/2/2018,1.0.9,4.4 and up
37,Floor Plan Creator,ART_AND_DESIGN,4.1,36639,Varies with device,"5,000,000+",Free,0,Everyone,Art & Design,7/14/2018,Varies with device,2.3.3 and up
38,PIP Camera - PIP Collage Maker,ART_AND_DESIGN,4.7,158,11M,"10,000+",Free,0,Everyone,Art & Design,11/29/2017,1.3,4.0.3 and up
39,How To Color Disney Princess - Coloring Pages,ART_AND_DESIGN,4.0,591,9.4M,"500,000+",Free,0,Everyone,Art & Design,3/31/2018,1,4.0 and up
40,Drawing Clothes Fashion Ideas,ART_AND_DESIGN,4.2,117,15M,"10,000+",Free,0,Everyone,Art & Design,7/20/2018,2.0.1,4.0.3 and up
41,Sad Poetry Photo Frames 2018,ART_AND_DESIGN,4.5,176,10M,"100,000+",Free,0,Everyone,Art & Design,4/2/2018,1,4.0.3 and up
42,Textgram - write on photos,ART_AND_DESIGN,4.4,295221,Varies with device,"10,000,000+",Free,0,Everyone,Art & Design,7/30/2018,Varies with device,Varies with device
43,Paint Splash!,ART_AND_DESIGN,3.8,2206,1.2M,"100,000+",Free,0,Everyone,Art & Design;Creativity,4/15/2018,1.46,4.1 and up
44,Popsicle Sticks and Similar DIY Craft Ideas,ART_AND_DESIGN,4.2,26,12M,"10,000+",Free,0,Everyone,Art & Design,1/3/2018,1.0.0,4.1 and up
45,"Canva: Poster, banner, card maker & graphic de...",ART_AND_DESIGN,4.7,174531,24M,"10,000,000+",Free,0,Everyone,Art & Design,7/31/2018,1.6.1,4.1 and up
46,Install images with music to make video withou...,ART_AND_DESIGN,4.6,1070,26M,"100,000+",Free,0,Everyone,Art & Design,11/14/2017,1.6,4.1 and up
47,Little Teddy Bear Colouring Book Game,ART_AND_DESIGN,4.2,85,8.0M,"100,000+",Free,0,Everyone,Art & Design,12/17/2017,2.0.0,4.1 and up
48,How To Draw Food,ART_AND_DESIGN,4.3,845,7.9M,"100,000+",Free,0,Everyone,Art & Design,5/28/2018,1,2.3 and up
49,Monster Truck Stunt 3D 2019,AUTO_AND_VEHICLES,4.2,367,25M,"100,000+",Free,0,Everyone,Auto & Vehicles,5/10/2018,1,4.0.3 and up

In [5]:
Google_Play.tail(50)

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
10791,Winter Wonderland,GAME,4.0,1287,38M,"50,000+",Free,0,Everyone,Word,12/18/2013,1,2.2 and up
10792,Soccer Clubs Logo Quiz,GAME,4.2,21661,16M,"1,000,000+",Free,0,Everyone,Trivia,5/24/2018,1.3.81,4.0 and up
10793,Sid Story,GAME,4.4,28510,78M,"500,000+",Free,0,Teen,Card,8/1/2018,2.6.6,4.0.3 and up
10794,PopStar,FAMILY,NaN,13,5.7M,"1,000+",Free,0,Everyone,Casual,1/3/2018,1.6,4.3 and up
10795,Reindeer VPN - Proxy VPN,TOOLS,4.2,7339,4.0M,"100,000+",Free,0,Everyone,Tools,5/10/2018,1.74,4.1 and up
10796,Inf VPN - Global Proxy & Unlimited Free WIFI VPN,TOOLS,4.7,61445,7.8M,"1,000,000+",Free,0,Everyone,Tools,7/26/2018,1.9.734,4.1 and up
10797,Fuel Rewards® program,LIFESTYLE,4.6,32433,46M,"1,000,000+",Free,0,Everyone,Lifestyle,6/26/2018,2.9.1,5.0 and up
10798,Word Search Tab 1 FR,FAMILY,NaN,0,1020k,50+,Paid,$1.04,Everyone,Puzzle,2/6/2012,1.1,3.0 and up
10799,Fr Daoud Lamei,SOCIAL,4.7,2036,6.8M,"100,000+",Free,0,Everyone,Social,5/20/2018,1.72,4.0.3 and up
10800,FR Roster,TOOLS,4.1,174,12M,"5,000+",Free,0,Everyone,Tools,7/30/2018,6.04,4.4 and up
10801,Fr Ignacio Outreach,FAMILY,4.9,52,19M,"1,000+",Free,0,Everyone,Education,1/19/2018,1,4.4 and up
10802,FR: My Famous Lover,FAMILY,4.0,185,28M,"10,000+",Free,0,Teen,Entertainment,8/6/2015,1.3.0,3.0 and up
10803,Fatal Raid - No.1 Mobile FPS,GAME,4.3,56496,81M,"1,000,000+",Free,0,Teen,Action,8/7/2018,1.5.447,4.0 and up
10804,Poker Pro.Fr,GAME,4.2,5442,17M,"100,000+",Free,0,Teen,Card,5/22/2018,4.1.3,2.3 and up
10805,Scoreboard FR,LIFESTYLE,4.3,3,15M,100+,Free,0,Everyone,Lifestyle,8/7/2018,2.1,4.2 and up
10806,SnakeBite911 FR,MEDICAL,NaN,1,42M,500+,Free,0,Everyone,Medical,10/9/2017,1.2,4.1 and up
10807,My FR App,TOOLS,NaN,2,4.2M,100+,Free,0,Everyone,Tools,4/9/2018,1.283.0037,2.3.3 and up
10808,lesparticuliers.fr,LIFESTYLE,NaN,96,1.0M,"50,000+",Free,0,Everyone,Lifestyle,11/25/2014,1.5,2.3 and up
10809,Castle Clash: RPG War and Strategy FR,FAMILY,4.7,376223,24M,"1,000,000+",Free,0,Everyone,Strategy,7/18/2018,1.4.2,4.1 and up
10810,Fr Lupupa Sermons,BUSINESS,4.8,19,21M,100+,Free,0,Everyone,Business,6/12/2018,1,4.4 and up
10811,FR Plus 1.6,AUTO_AND_VEHICLES,NaN,4,3.9M,100+,Free,0,Everyone,Auto & Vehicles,7/24/2018,1.3.6,4.4W and up
10812,Fr Agnel Pune,FAMILY,4.1,80,13M,"1,000+",Free,0,Everyone,Education,6/13/2018,2.0.20,4.0.3 and up
10813,DICT.fr Mobile,BUSINESS,NaN,20,2.7M,"10,000+",Free,0,Everyone,Business,7/17/2018,2.1.10,4.1 and up
10814,FR: My Secret Pets!,FAMILY,4.0,785,31M,"50,000+",Free,0,Teen,Entertainment,6/3/2015,1.3.1,3.0 and up
10815,Golden Dictionary (FR-AR),BOOKS_AND_REFERENCE,4.2,5775,4.9M,"500,000+",Free,0,Everyone,Books & Reference,7/19/2018,7.0.4.6,4.2 and up
10816,FieldBi FR Offline,BUSINESS,NaN,2,6.8M,100+,Free,0,Everyone,Business,8/6/2018,2.1.8,4.1 and up
10817,HTC Sense Input - FR,TOOLS,4.0,885,8.0M,"100,000+",Free,0,Everyone,Tools,10/30/2015,1.0.612928,5.0 and up
10818,Gold Quote - Gold.fr,FINANCE,NaN,96,1.5M,"10,000+",Free,0,Everyone,Finance,5/19/2016,2.3,2.2 and up
10819,Fanfic-FR,BOOKS_AND_REFERENCE,3.3,52,3.6M,"5,000+",Free,0,Teen,Books & Reference,8/5/2017,0.3.4,4.1 and up
10820,Fr. Daoud Lamei,FAMILY,5.0,22,8.6M,"1,000+",Free,0,Teen,Education,6/27/2018,3.8.0,4.1 and up
10821,Poop FR,FAMILY,NaN,6,2.5M,50+,Free,0,Everyone,Entertainment,5/29/2018,1,4.0.3 and up
10822,PLMGSS FR,PRODUCTIVITY,NaN,0,3.1M,10+,Free,0,Everyone,Productivity,12/1/2017,1,4.4 and up
10823,List iptv FR,VIDEO_PLAYERS,NaN,1,2.9M,100+,Free,0,Everyone,Video Players & Editors,4/22/2018,1,4.0.3 and up
10824,Cardio-FR,MEDICAL,NaN,67,82M,"10,000+",Free,0,Everyone,Medical,7/31/2018,2.2.2,4.4 and up
10825,Naruto & Boruto FR,SOCIAL,NaN,7,7.7M,100+,Free,0,Teen,Social,2/2/2018,1,4.0 and up
10826,Frim: get new friends on local chat rooms,SOCIAL,4.0,88486,Varies with device,"5,000,000+",Free,0,Mature 17+,Social,3/23/2018,Varies with device,Varies with device
10827,Fr Agnel Ambarnath,FAMILY,4.2,117,13M,"5,000+",Free,0,Everyone,Education,6/13/2018,2.0.20,4.0.3 and up
10828,Manga-FR - Anime Vostfr,COMICS,3.4,291,13M,"10,000+",Free,0,Everyone,Comics,5/15/2017,2.0.1,4.0 and up
10829,Bulgarian French Dictionary Fr,BOOKS_AND_REFERENCE,4.6,603,7.4M,"10,000+",Free,0,Everyone,Books & Reference,6/19/2016,2.96,4.1 and up
10830,News Minecraft.fr,NEWS_AND_MAGAZINES,3.8,881,2.3M,"100,000+",Free,0,Everyone,News & Magazines,1/20/2014,1.5,1.6 and up
10831,payermonstationnement.fr,MAPS_AND_NAVIGATION,NaN,38,9.8M,"5,000+",Free,0,Everyone,Maps & Navigation,6/13/2018,2.0.148.0,4.0 and up
10832,FR Tides,WEATHER,3.8,1195,582k,"100,000+",Free,0,Everyone,Weather,2/16/2014,6,2.1 and up
10833,Chemin (fr),BOOKS_AND_REFERENCE,4.8,44,619k,"1,000+",Free,0,Everyone,Books & Reference,3/23/2014,0.8,2.2 and up
10834,FR Calculator,FAMILY,4.0,7,2.6M,500+,Free,0,Everyone,Education,6/18/2017,1.0.0,4.1 and up
10835,FR Forms,BUSINESS,NaN,0,9.6M,10+,Free,0,Everyone,Business,9/29/2016,1.1.5,4.0 and up
10836,Sya9a Maroc - FR,FAMILY,4.5,38,53M,"5,000+",Free,0,Everyone,Education,7/25/2017,1.48,4.1 and up
10837,Fr. Mike Schmitz Audio Teachings,FAMILY,5.0,4,3.6M,100+,Free,0,Everyone,Education,7/6/2018,1,4.1 and up
10838,Parkinson Exercices FR,MEDICAL,NaN,3,9.5M,"1,000+",Free,0,Everyone,Medical,1/20/2017,1,2.2 and up
10839,The SCP Foundation DB fr nn5n,BOOKS_AND_REFERENCE,4.5,114,Varies with device,"1,000+",Free,0,Mature 17+,Books & Reference,1/19/2015,Varies with device,Varies with device
10840,iHoroscope - 2018 Daily Horoscope & Astrology,LIFESTYLE,4.5,398307,19M,"10,000,000+",Free,0,Everyone,Lifestyle,7/25/2018,Varies with device,Varies with device

In [6]:
Google_Play.sample(50)

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
1144,Webull - Stock Quotes & Free Stock Trading,FINANCE,4.3,34861,Varies with device,"1,000,000+",Free,0,Everyone,Finance,8/3/2018,Varies with device,Varies with device
4119,F-Secure SAFE,TOOLS,4.3,9433,9.3M,"500,000+",Free,0,Everyone,Tools,7/30/2018,17.4.0014017,5.0 and up
4478,Android P Stock Wallpapers,PERSONALIZATION,4.5,16,3.7M,"1,000+",Free,0,Everyone,Personalization,8/1/2018,2.3.0,5.0 and up
2052,Farming Simulator 14,FAMILY,4.5,530854,51M,"10,000,000+",Free,0,Everyone,Simulation;Action & Adventure,7/17/2017,1.4.4,2.3.3 and up
225,Secure Folder,BUSINESS,3.8,14760,8.6M,"50,000,000+",Free,0,Everyone,Business,1/31/2018,1.1.07.6,7.0 and up
3171,Qatar Airways,TRAVEL_AND_LOCAL,4.3,11182,62M,"1,000,000+",Free,0,Everyone,Travel & Local,7/30/2018,11.26,4.1 and up
7028,FunnyPixels - Color by number Sandbox,FAMILY,4.6,1977,3.8M,"100,000+",Free,0,Everyone,Entertainment,2/21/2018,1.0.4,4.0.3 and up
4058,Z Ringtones PREMIUM 2018,PERSONALIZATION,4.5,10158,3.6M,"500,000+",Free,0,Everyone,Personalization,3/1/2018,1.5,4.0.3 and up
10387,Toy Attack,GAME,4.2,3878,69M,"500,000+",Free,0,Everyone,Action,4/4/2018,1.9,4.0.3 and up
3680,Music - Mp3 Player,VIDEO_PLAYERS,4.4,259605,3.1M,"10,000,000+",Free,0,Everyone,Video Players & Editors,8/3/2018,1.6.1,4.0.3 and up
3393,OnePlus Icon Pack,PERSONALIZATION,4.8,440,920k,"500,000+",Free,0,Everyone,Personalization,5/23/2018,1.9.2.180419172639.dbf3246,5.0 and up
1742,Traffic Racer,GAME,4.5,5387639,53M,"100,000,000+",Free,0,Everyone,Racing,2/27/2018,2.5,4.1 and up
7336,FAV KWGT,PERSONALIZATION,4.9,88,66M,"1,000+",Paid,$0.99,Everyone,Personalization,7/26/2018,8,5.0 and up
4071,Eventbrite - Discover popular events & nearby fun,FAMILY,4.4,63773,8.8M,"5,000,000+",Free,0,Everyone,Entertainment,7/30/2018,5.7.2,5.0 and up
8055,CX-95WIFI,LIFESTYLE,NaN,6,11M,500+,Free,0,Everyone,Lifestyle,6/2/2017,2.1,4.0 and up
7726,CQ SIGNAL PRO 5,FINANCE,NaN,0,1.6M,10+,Free,0,Everyone,Finance,4/17/2017,4,4.1 and up
9975,Home Workout - No Equipment,HEALTH_AND_FITNESS,4.8,432160,15M,"10,000,000+",Free,0,Everyone,Health & Fitness,6/28/2018,Varies with device,Varies with device
7096,Save.ca,SHOPPING,3.7,2094,34M,"100,000+",Free,0,Everyone,Shopping,7/2/2018,4.8.18.12,4.1 and up
2597,Whisper,SOCIAL,4.1,205803,Varies with device,"5,000,000+",Free,0,Teen,Social,7/18/2018,Varies with device,Varies with device
15,Learn To Draw Kawaii Characters,ART_AND_DESIGN,3.2,55,2.7M,"5,000+",Free,0,Everyone,Art & Design,6/6/2018,NaN,4.2 and up
8635,"Polaris Office - Word, Docs, Sheets, Slide, PDF",PRODUCTIVITY,4.3,549900,60M,"10,000,000+",Free,0,Everyone,Productivity,7/18/2018,7.3.30,4.1 and up
7062,Südtirol2Go,MAPS_AND_NAVIGATION,3.3,555,31M,"50,000+",Free,0,Everyone,Maps & Navigation,12/20/2017,2.1.2,4.0 and up
1495,Kitchen Island Ideas,HOUSE_AND_HOME,4.0,515,5.8M,"50,000+",Free,0,Everyone,House & Home,5/30/2015,1.5,3.0 and up
1325,Seven - 7 Minute Workout Training Challenge,HEALTH_AND_FITNESS,4.5,75571,Varies with device,"1,000,000+",Free,0,Everyone,Health & Fitness,8/3/2018,7.2.5,Varies with device
7419,CJ's Tire & Automotive,AUTO_AND_VEHICLES,4.0,5,34M,"1,000+",Free,0,Everyone,Auto & Vehicles,7/30/2018,2.8,2.3.3 and up
8753,IHOP®,FOOD_AND_DRINK,4.2,441,24M,"100,000+",Free,0,Everyone,Food & Drink,4/3/2018,2.2.0,4.1 and up
115,Photo Editor 2018,BEAUTY,4.5,134,17M,"10,000+",Free,0,Everyone,Beauty,3/1/2018,1.2,4.0.3 and up
5875,A-Z App Store,PRODUCTIVITY,3.2,2728,4.4M,"500,000+",Free,0,Everyone,Productivity,10/5/2016,1.0.5,4.1 and up
9307,EF Financial Control Free,FINANCE,4.4,58,3.7M,"10,000+",Free,0,Everyone,Finance,5/6/2018,1.9.0,4.0.3 and up
1408,Monitor Your Weight,HEALTH_AND_FITNESS,4.5,126017,4.3M,"5,000,000+",Free,0,Everyone,Health & Fitness,7/5/2018,4.9.8.1,4.0 and up
3398,ZEDGE™ Ringtones & Wallpapers,PERSONALIZATION,4.6,6466641,Varies with device,"100,000,000+",Free,0,Teen,Personalization,7/19/2018,Varies with device,Varies with device
8198,DB Navigator,MAPS_AND_NAVIGATION,4.0,119685,20M,"10,000,000+",Free,0,Everyone,Maps & Navigation,7/2/2018,18.06.p03.02,4.0.3 and up
7412,CJ SO COOL,FAMILY,4.5,145,14M,"10,000+",Free,0,Everyone,Entertainment,7/11/2018,1,4.2 and up
3422,Wallpapers HD,PERSONALIZATION,4.6,484981,2.1M,"10,000,000+",Free,0,Everyone,Personalization,11/28/2016,1.7.1,3.0 and up
64,DMV Permit Practice Test 2018 Edition,AUTO_AND_VEHICLES,4.9,6090,27M,"100,000+",Free,0,Everyone,Auto & Vehicles,7/3/2018,1.7,4.2 and up
770,GRE Tutor,EDUCATION,4.0,275,2.3M,"50,000+",Free,0,Everyone,Education,12/2/2013,2.9,2.1 and up
6331,One Launcher,PERSONALIZATION,4.3,26601,5.4M,"1,000,000+",Free,0,Everyone,Personalization,7/16/2018,26.1.0.20180713,2.3.3 and up
5495,Battle Gems (AdventureQuest),FAMILY,4.4,48427,Varies with device,"500,000+",Free,0,Everyone 10+,Puzzle,3/31/2018,Varies with device,Varies with device
1780,Looper!,GAME,4.6,48256,62M,"1,000,000+",Free,0,Everyone,Puzzle,7/20/2018,1.2.0,4.1 and up
8739,Find Fast Food,SHOPPING,3.3,272,785k,"100,000+",Free,0,Everyone,Shopping,11/11/2012,1.1.6,2.2 and up
555,Heart mill,DATING,3.3,4631,45M,"100,000+",Free,0,Mature 17+,Dating,8/4/2018,5.2.14,5.0 and up
7193,CE Map - Interactive Conan Exiles Map,MAPS_AND_NAVIGATION,4.5,62,1.6M,"1,000+",Paid,$0.99,Everyone,Maps & Navigation,6/30/2018,1.3,4.0 and up
1468,"realestate.com.au - Buy, Rent & Sell Property",HOUSE_AND_HOME,3.8,14653,Varies with device,"1,000,000+",Free,0,Everyone,House & Home,7/16/2018,Varies with device,Varies with device
8148,signály.cz,SOCIAL,NaN,38,881k,"1,000+",Free,0,Everyone,Social,5/9/2013,1.1,2.2 and up
8475,Super DK vs Kong Brother Advanced Free Classic,GAME,3.8,66,38M,"10,000+",Free,0,Everyone,Arcade,7/17/2018,1.2,4.1 and up
420,UC Browser - Fast Download Private & Secure,COMMUNICATION,4.5,17714850,40M,"500,000,000+",Free,0,Teen,Communication,8/2/2018,12.8.5.1121,4.0 and up
10634,Florida Map offline,TRAVEL_AND_LOCAL,4.6,8,18M,"1,000+",Free,0,Everyone,Travel & Local,6/22/2018,1.73,4.3 and up
2168,Children Educational Game Full,FAMILY,4.7,30,Varies with device,"1,000+",Paid,$7.49,Everyone,Educational;Education,5/16/2018,Varies with device,Varies with device
4653,[verify-U] VideoIdent,COMMUNICATION,2.9,83,13M,"10,000+",Free,0,Everyone,Communication,4/26/2018,2.4.0,5.0 and up
9047,DX Simulation for Decade Henshin Belt 2018,FAMILY,NaN,23,10M,"5,000+",Free,0,Everyone,Simulation,8/6/2018,1.6,4.0 and up

In [7]:
Google_Play.describe()

            Rating       Reviews
count  9367.000000  1.084100e+04
mean      4.191513  4.441119e+05
std       0.515735  2.927629e+06
min       1.000000  0.000000e+00
25%       4.000000  3.800000e+01
50%       4.300000  2.094000e+03
75%       4.500000  5.476800e+04
max       5.000000  7.815831e+07

In [8]:
print('Total Duplicats :\n' , Google_Play.duplicated().sum())

print('Null Values Per Column :\n',Google_Play.isnull().sum())

print('Total Null Values :\n',Google_Play.isnull().sum().sum())

Total Duplicats :
 483
Null Values Per Column :
 App                  0
Category             1
Rating            1474
Reviews              0
Size                 0
Installs             0
Type                 1
Price                0
Content Rating       0
Genres               1
Last Updated         0
Current Ver          9
Android Ver          2
dtype: int64
Total Null Values :
 1488

Step 4 : Data Cleaning

In [9]:
# Remove Duplicates
Google_Play.drop_duplicates(inplace=True)

In [10]:
print('Total Duplicats :\n' , Google_Play.duplicated().sum())

Total Duplicats :
 0

In [11]:
# Remove Null Values
Google_Play.dropna(inplace=True)

In [12]:
print('Total Null Values :\n',Google_Play.isnull().sum().sum())

Total Null Values :
 0

In [13]:
# Change Data Type

Google_Play['Price'] = Google_Play['Price'].str.replace('$', '', regex=False)
Google_Play['Price'] = Google_Play['Price'].astype(float)

Google_Play['Last Updated'] = pd.to_datetime(Google_Play['Last Updated'])

In [14]:
# Handling Columns

Google_Play['Installs'] = (
    Google_Play['Installs']
    .str.replace('+', '', regex=False)
    .str.replace(',', '', regex=False)
    .astype(int)
)

Step 5 : Feature Engineering

In [18]:
# Export Totla Sales

Google_Play['Total Sales']=sum(Google_Play['Price'])

Step 6 : Export Dataset

In [20]:
Google_Play.to_csv(r'C:\Users\Lap Tech\Desktop\Google Play.csv', index=False)